### OracleDB 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@//192.168.0.3 :1521/xepdb1
spring.datasource.url=jdbc:oracle:thin:@//210.178.108.186:1521/xepdb1
spring.datasource.username=ERP
spring.datasource.password=choongang



# H2 인메모리 DB 사용 (더 안전)
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=Oracle
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true